<script type="text/javascript">
    <?php
        // Testcode...
        $helper = $this->getOverheatHelper();
        /*$helper->addProduct(Mage::getModel('catalog/product')->load(1));
        $helper->createProductList('product_list');
        $helper->addProduct(Mage::getModel('catalog/product')->load(1), null, 'product_list');
        $helper->addProduct(Mage::getModel('catalog/product')->load(2), null, 'product_list');*/
    ?>
    <?php echo $this->getJavascript(); ?>
</script>
